name: raviqqe/pnpm-publish
description: pnpm publish as a GitHub Action
branding:
  icon: book
  color: orange
inputs:
  build_script:
    description: A build script
    required: false
    default: build
  directory:
    description: A directory where a `pnpm-workspace.yaml` file exists
    required: false
    default: .
  release:
    description: A flag to release packages
    required: false
outputs: {}
runs:
  using: composite
  steps:
    - run: pnpm i --frozen-lockfile
      shell: bash
      working-directory: ${{ inputs.directory }}
    - run: pnpm -r ${{ inputs.build_script }}
      shell: bash
      working-directory: ${{ inputs.directory }}
    - run: >
        pnpm -r publish --access public
        ${{ inputs.release != 'true' && '--dry-run --no-git-checks' || '' }}
      shell: bash
      working-directory: ${{ inputs.directory }}
