name: raviqqe/pnpm-publish
description: pnpm publish as a GitHub Action
branding:
  icon: book
  color: orange
inputs:
  build_script:
    description: A build script
    required: false
    default: build
  directory:
    description: A directory where a `pnpm-workspace.yaml` file exists
    required: false
    default: .
  npm_token:
    description: NPM token
    required: false
outputs: {}
runs:
  using: composite
  steps:
    - run: pnpm -r ${{ inputs.build_script }}
      shell: bash
      working-directory: ${{ inputs.directory }}
    - run: npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
      shell: bash
      env:
        NPM_TOKEN: ${{ inputs.npm_token }}
    - run: >
        pnpm -r publish --access public
        ${{ !inputs.npm_token && '--dry-run --no-git-checks' || '' }}
      shell: bash
      working-directory: ${{ inputs.directory }}
