name: test
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
        with:
          package_json_file: test/package.json
      - uses: actions/setup-node@v4
        with:
          node-version: latest
      - run: pnpm i --frozen-lockfile
        working-directory: test
      - uses: ./.
        with:
          directory: test
  spell_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: streetsidesoftware/cspell-action@v7
        with:
          files: "**/*.md"
